# Generated by Django 5.2.10 on 2026-01-15 08:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postblock_options_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='المحتوى'),
        ),
    ]
