# Generated by Django 5.2.10 on 2026-01-13 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Placement Name')),
                ('code', models.SlugField(unique=True)),
                ('placement_type', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('between_posts', 'Between Posts'), ('popup', 'Popup'), ('in_content', 'In Content')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(default=300)),
                ('height', models.PositiveIntegerField(default=250)),
                ('active', models.BooleanField(default=True)),
                ('max_ads', models.PositiveIntegerField(default=5, help_text='Maximum number of ads to show in this placement')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority placements are shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad Title')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Image'), ('text', 'Text Ad'), ('html', 'HTML Code'), ('video', 'Video Ad')], default='banner', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/banners/%Y/%m/', verbose_name='Banner Image')),
                ('text_content', models.TextField(blank=True, verbose_name='Text Content')),
                ('html_code', models.TextField(blank=True, verbose_name='HTML Code')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('link', models.URLField(verbose_name='Destination URL')),
                ('target_blank', models.BooleanField(default=True, verbose_name='Open in new tab')),
                ('nofollow', models.BooleanField(default=True, verbose_name='Add nofollow attribute')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority ads are shown first', verbose_name='Priority')),
                ('advertiser_name', models.CharField(blank=True, max_length=100, verbose_name='Advertiser Name')),
                ('advertiser_email', models.EmailField(blank=True, max_length=254, verbose_name='Advertiser Email')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_impression', models.DateTimeField(blank=True, null=True)),
                ('last_click', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.adplacement', verbose_name='Ad Placement')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-priority', '-start_date'],
                'indexes': [models.Index(fields=['active', 'start_date', 'end_date'], name='advertiseme_active_e311b7_idx'), models.Index(fields=['placement', 'active'], name='advertiseme_placeme_387b69_idx'), models.Index(fields=['ad_type'], name='advertiseme_ad_type_ea86f0_idx')],
            },
        ),
    ]
